/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nacho
 */
public class ReservaSalonPremium extends javax.swing.JDialog {

    /**
     * Creates new form NewJFrame
     */
    public ReservaSalonPremium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellidos = new javax.swing.JTextField();
        jTFDni = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jSFecha = new javax.swing.JSpinner();
        jSNumPersonas = new javax.swing.JSpinner();
        jToolBarTipoEvento = new javax.swing.JToolBar();
        jRadioButtonBanquete = new javax.swing.JRadioButton();
        jRadioButtonJornada = new javax.swing.JRadioButton();
        jRadioCongreso = new javax.swing.JRadioButton();
        jRadioButtonBoda = new javax.swing.JRadioButton();
        jComboBoxCapilla = new javax.swing.JComboBox<>();
        jToolBarCatering = new javax.swing.JToolBar();
        jRadioButtonBuffet = new javax.swing.JRadioButton();
        jRadioButtonWok = new javax.swing.JRadioButton();
        jRadioButtonCarta = new javax.swing.JRadioButton();
        jRadioButtonChef = new javax.swing.JRadioButton();
        jBTarifas = new javax.swing.JButton();
        jBReservar = new javax.swing.JButton();
        jPanelCongreso = new javax.swing.JPanel();
        jSNumJornadas = new javax.swing.JSpinner();
        jToolBarHabitacion = new javax.swing.JToolBar();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Reserva del Salón Premium");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 800));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));

        jPanel1.setEnabled(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jTFNombre.setToolTipText("Introduzca su nombre");
        jTFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jTFNombre.setMaximumSize(new java.awt.Dimension(700, 600));
        jTFNombre.setPreferredSize(new java.awt.Dimension(700, 39));

        jTFApellidos.setToolTipText("Introduzca sus apellidos");
        jTFApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        jTFApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApellidosActionPerformed(evt);
            }
        });

        jTFDni.setToolTipText("Introduzca su DNI");
        jTFDni.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        jTFTelefono.setToolTipText("Introduzca su teléfono");
        jTFTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono"));
        jTFTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefonoActionPerformed(evt);
            }
        });

        jSFecha.setModel(new javax.swing.SpinnerDateModel());
        jSFecha.setToolTipText("Fecha que quiere reservar");
        jSFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha"));
        jSFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSNumPersonas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSNumPersonas.setToolTipText("Numero de personas que va a acudir al evento");
        jSNumPersonas.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de personas"));

        jToolBarTipoEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de evento"));
        jToolBarTipoEvento.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarTipoEvento.setRollover(true);
        jToolBarTipoEvento.setEnabled(false);

        buttonGroup1.add(jRadioButtonBanquete);
        jRadioButtonBanquete.setSelected(true);
        jRadioButtonBanquete.setText("Banquete");
        jToolBarTipoEvento.add(jRadioButtonBanquete);
        jRadioButtonBanquete.getAccessibleContext().setAccessibleName("eve_banquete");

        buttonGroup1.add(jRadioButtonJornada);
        jRadioButtonJornada.setText("Jornada");
        jToolBarTipoEvento.add(jRadioButtonJornada);
        jRadioButtonJornada.getAccessibleContext().setAccessibleName("eve_jornada");

        buttonGroup1.add(jRadioCongreso);
        jRadioCongreso.setText("Congreso");
        jToolBarTipoEvento.add(jRadioCongreso);
        jRadioCongreso.getAccessibleContext().setAccessibleName("eve_congreso");

        buttonGroup1.add(jRadioButtonBoda);
        jRadioButtonBoda.setText("Boda");
        jRadioButtonBoda.setToolTipText("Debe indicar si necesita capilla");
        jToolBarTipoEvento.add(jRadioButtonBoda);
        jRadioButtonBoda.getAccessibleContext().setAccessibleName("eve_boda");

        jComboBoxCapilla.setMaximumRowCount(3);
        jComboBoxCapilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------", "Con capilla", "Sin capilla", " " }));
        jComboBoxCapilla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxCapilla.setEditor(null);
        jComboBoxCapilla.setMaximumSize(new java.awt.Dimension(180, 300));
        jComboBoxCapilla.setMinimumSize(new java.awt.Dimension(0, 0));
        jComboBoxCapilla.setPreferredSize(new java.awt.Dimension(50, 24));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioButtonBoda, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jComboBoxCapilla, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jComboBoxCapilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapillaActionPerformed(evt);
            }
        });
        jToolBarTipoEvento.add(jComboBoxCapilla);

        jToolBarCatering.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de catering"));
        jToolBarCatering.setFloatable(false);
        jToolBarCatering.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBarCatering.setRollover(true);
        jToolBarCatering.setEnabled(false);

        buttonGroup2.add(jRadioButtonBuffet);
        jRadioButtonBuffet.setSelected(true);
        jRadioButtonBuffet.setText("Bufet");
        jToolBarCatering.add(jRadioButtonBuffet);
        jRadioButtonBuffet.getAccessibleContext().setAccessibleName("cat_bufet");

        buttonGroup2.add(jRadioButtonWok);
        jRadioButtonWok.setText("Wok");
        jToolBarCatering.add(jRadioButtonWok);
        jRadioButtonWok.getAccessibleContext().setAccessibleName("cat_wok");

        buttonGroup2.add(jRadioButtonCarta);
        jRadioButtonCarta.setText("Carta");
        jRadioButtonCarta.setToolTipText("Elija entre nuestro variadas cartas");
        jToolBarCatering.add(jRadioButtonCarta);
        jRadioButtonCarta.getAccessibleContext().setAccessibleName("cat_carta");

        buttonGroup2.add(jRadioButtonChef);
        jRadioButtonChef.setText("Chef");
        jRadioButtonChef.setToolTipText("Nuestro chef se pondra en contacto con usted para determinar el menu");
        jToolBarCatering.add(jRadioButtonChef);
        jRadioButtonChef.getAccessibleContext().setAccessibleName("cat_chef");
        jRadioButtonChef.getAccessibleContext().setAccessibleDescription("");

        jBTarifas.setText("Tarifas");
        jBTarifas.setToolTipText("Vea nuestras tarifas actuales");
        jBTarifas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTarifasActionPerformed(evt);
            }
        });

        jBReservar.setText("Reservar");
        jBReservar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelCongreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Congreso"));
        jPanelCongreso.setFocusable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioCongreso, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jPanelCongreso, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jSNumJornadas.setToolTipText("Indique el numero de dias que va a durar su congreso");
        jSNumJornadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de jornadas"));
        jSNumJornadas.setMaximumSize(new java.awt.Dimension(150, 37));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioCongreso, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jSNumJornadas, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jToolBarHabitacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Necesita habitaciones"));
        jToolBarHabitacion.setRollover(true);
        jToolBarHabitacion.setToolTipText("Indique si necesita habitaciones");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioCongreso, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jToolBarHabitacion, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("Si");
        jRadioButton9.setFocusable(false);
        jRadioButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioCongreso, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jRadioButton9, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jToolBarHabitacion.add(jRadioButton9);

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("No");
        jRadioButton10.setFocusable(false);
        jRadioButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRadioCongreso, org.jdesktop.beansbinding.ELProperty.create("${selected}"), jRadioButton10, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jToolBarHabitacion.add(jRadioButton10);

        javax.swing.GroupLayout jPanelCongresoLayout = new javax.swing.GroupLayout(jPanelCongreso);
        jPanelCongreso.setLayout(jPanelCongresoLayout);
        jPanelCongresoLayout.setHorizontalGroup(
            jPanelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSNumJornadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCongresoLayout.createSequentialGroup()
                .addComponent(jToolBarHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCongresoLayout.setVerticalGroup(
            jPanelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCongresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSNumJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jSNumJornadas.getAccessibleContext().setAccessibleName("eve_congreso_jornadas");
        jToolBarHabitacion.getAccessibleContext().setAccessibleName("eve_congreso_habitaciones");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jToolBarCatering, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addComponent(jToolBarTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTFDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBTarifas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanelCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53))))
                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jSFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(155, 155, 155)
                            .addComponent(jSNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCongreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jToolBarCatering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToolBarTipoEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jBTarifas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addComponent(jBReservar)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(40, 40, 40))
        );

        jTFNombre.getAccessibleContext().setAccessibleName("nombre");
        jTFNombre.getAccessibleContext().setAccessibleDescription("");
        jTFApellidos.getAccessibleContext().setAccessibleName("apellidos");
        jTFApellidos.getAccessibleContext().setAccessibleDescription("");
        jTFDni.getAccessibleContext().setAccessibleName("dni");
        jTFDni.getAccessibleContext().setAccessibleDescription("");
        jTFTelefono.getAccessibleContext().setAccessibleName("telefono");
        jTFTelefono.getAccessibleContext().setAccessibleDescription("");
        jSFecha.getAccessibleContext().setAccessibleName("fecha");
        jSFecha.getAccessibleContext().setAccessibleDescription("");
        jSNumPersonas.getAccessibleContext().setAccessibleName("num_personas");
        jSNumPersonas.getAccessibleContext().setAccessibleDescription("");
        jBTarifas.getAccessibleContext().setAccessibleName("Muestra la tarifa de nuestro Salon Premium");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("reserva_s_premium");

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCapillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCapillaActionPerformed

    private void jBTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTarifasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTarifasActionPerformed

    private void jTFApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApellidosActionPerformed

    private void jTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonPremium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaSalonPremium().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBReservar;
    private javax.swing.JButton jBTarifas;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxCapilla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCongreso;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButtonBanquete;
    private javax.swing.JRadioButton jRadioButtonBoda;
    private javax.swing.JRadioButton jRadioButtonBuffet;
    private javax.swing.JRadioButton jRadioButtonCarta;
    private javax.swing.JRadioButton jRadioButtonChef;
    private javax.swing.JRadioButton jRadioButtonJornada;
    private javax.swing.JRadioButton jRadioButtonWok;
    private javax.swing.JRadioButton jRadioCongreso;
    private javax.swing.JSpinner jSFecha;
    private javax.swing.JSpinner jSNumJornadas;
    private javax.swing.JSpinner jSNumPersonas;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JToolBar jToolBarCatering;
    private javax.swing.JToolBar jToolBarHabitacion;
    private javax.swing.JToolBar jToolBarTipoEvento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
