
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nacho
 */
public class VisualizarEmpleados extends javax.swing.JDialog {

    String[] cabecera = new String[]{"EMP-NO", "NOMBRE", "EMP-NO-JEFE", "NOMBRE JEFE", "OFICIO", "DEPT_NO", "NOMBRE-DEP"}; 
    DefaultTableModel modelo;
    String[] fila;
    String resultadoString;
    
    public VisualizarEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(cabecera);
        
        
        initComponents();
        jTable1.setEnabled(false);
        
    }
    
    public void actualizarDatos(ResultSet resultado){
        
        cabecera = new String[]{"EMP-NO", "NOMBRE", "EMP-NO-JEFE", "NOMBRE JEFE", "OFICIO", "DEPT_NO", "NOMBRE-DEP"}; 
    
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(cabecera);
        jTable1.setModel(modelo);
        jTable1.setEnabled(false);
       
        try {
            while (resultado.next ()) {
                resultadoString="";
                resultadoString=resultadoString+resultado.getString(1)+",";
                resultadoString=resultadoString+resultado.getString(2)+",";
                if(resultado.getObject(3)==null){
                    resultadoString=resultadoString+"NO TIENE,";
                } else {
                    resultadoString=resultadoString+resultado.getString(3)+",";
                }    
                if(resultado.getObject(4)==null){
                    resultadoString=resultadoString+"NO TIENE,";
                } else {
                    resultadoString=resultadoString+resultado.getString(4)+",";
                }    
                resultadoString=resultadoString+resultado.getString(5)+",";
                resultadoString=resultadoString+resultado.getString(6)+",";
                resultadoString=resultadoString+resultado.getString(7);
                fila = resultadoString.split(",");
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VisualizarEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void visualizarEmpleados(ResultSet resultado){
        
        cabecera = new String[]{"EMP-NUM", "APELL", "OFICIO", "DIR", "FECHA", "SALARIO", "COMISION", "DEPT-NO"}; 
    
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(cabecera);
        jTable1.setModel(modelo);
        jTable1.setEnabled(false);
       
        try {
            while (resultado.next ()) {
                resultadoString="";
                resultadoString=resultadoString+resultado.getString(1)+",";
                resultadoString=resultadoString+resultado.getString(2)+",";
                if(resultado.getObject(3)==null){
                    resultadoString=resultadoString+"NO TIENE,";
                } else {
                    resultadoString=resultadoString+resultado.getString(3)+",";
                }    
                if(resultado.getObject(4)==null){
                    resultadoString=resultadoString+"NO TIENE,";
                } else {
                    resultadoString=resultadoString+resultado.getString(4)+",";
                }    
                resultadoString=resultadoString+resultado.getString(5)+",";
                resultadoString=resultadoString+resultado.getString(6)+",";
                resultadoString=resultadoString+resultado.getString(7)+",";
                resultadoString=resultadoString+resultado.getString(8);
                fila = resultadoString.split(",");
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VisualizarEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(modelo);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
