
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nacho
 */
public class VentanaListadoCuentas extends javax.swing.JPanel {

    /**
     * Creates new form VentanaListadoCuentas
     */
    public VentanaListadoCuentas() {
        initComponents();
    }
    
    /**
     * nos devuelve el codigo
     * el jtable esta llamado desde el codigo creado desde el swing
     * @param diferenciador
     * @return 
     */
    public JPanel VentanaListadoCuentas(String diferenciador) {
        System.out.println("Se ha pulsado el boton "+diferenciador);
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuentas = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        jTableCuentas.setBackground(new java.awt.Color(204, 204, 204));
        jTableCuentas.setModel(AplicacionCuentaBancaria.cuentaBancaria.datosTabla);
        jScrollPane1.setViewportView(jTableCuentas);
        if (jTableCuentas.getColumnModel().getColumnCount() > 0) {
            jTableCuentas.getColumnModel().getColumn(0).setResizable(false);
            jTableCuentas.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuentas;
    // End of variables declaration//GEN-END:variables
}
