
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


/**
 *
 * @author Nacho
 */
public class VentanaVarios extends javax.swing.JPanel {

    String diferenciador, saldo, cuenta;
    
    
    public VentanaVarios() {
        initComponents();
    }
    
    /**Nos sirve para ingresar, retirar y ver el saldo
     * 
     * @param diferenciador: para decirle que nos tiene que mostrar
     * @param cuenta: le pasamos el numero de cuenta
     * @return nos devuelve un jpanel
     */
    public JPanel VentanaVarios(String diferenciador, String cuenta ) {
        System.out.println("Se ha pulsado el boton "+diferenciador);
        
        this.diferenciador=diferenciador;
        this.cuenta=cuenta;
        
        //obtenemos el saldo
        for (CuentaBancaria obj : AplicacionCuentaBancaria.cuentaBancaria.getListadoObjetos()) {
            if (obj.getCcc().equals(cuenta)){
                
            saldo=Double.toString(obj.getSaldo());
            }
        }
        
        //si es ingresar hacemos visibles los campos y cambiamos el texto 
        if (diferenciador.equals("Ingresar")){
            
            jTFVarios.setText("");
            jLSaldo.setVisible(false);
            jTFSaldo.setVisible(false);
            jLVarios.setVisible(true);
            jLVarios.setText(diferenciador);
            jTFVarios.setVisible(true);
            jBVarios.setText(diferenciador);
            jBVarios.setVisible(true);
        }
        
        //si es retirar hacemos visibles los campos y cambiamos el texto
        if (diferenciador.equals("Retirar")){
            jTFVarios.setText("");
            jLSaldo.setVisible(false);
            jTFSaldo.setVisible(false);
            jLVarios.setVisible(true);
            jLVarios.setText(diferenciador);
            jTFVarios.setVisible(true);
            jBVarios.setText(diferenciador);
            jBVarios.setVisible(true);
        }
        
        //si es saldo hacemos visibles los campos y cambiamos el texto
        if (diferenciador.equals("Saldo")){
            jLSaldo.setVisible(true);
            jTFSaldo.setText(saldo);
            jTFSaldo.setVisible(true);
            jLVarios.setVisible(false);
            jTFVarios.setVisible(false);
            jBVarios.setVisible(false);
            
        }
        
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSaldo = new javax.swing.JLabel();
        jTFSaldo = new javax.swing.JTextField();
        jBVarios = new javax.swing.JButton();
        jLVarios = new javax.swing.JLabel();
        jTFVarios = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        jLSaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSaldo.setText("Saldo");

        jTFSaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTFSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFSaldo.setEnabled(false);

        jBVarios.setText("Ingresar");
        jBVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVariosActionPerformed(evt);
            }
        });

        jLVarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVarios.setText(" ");

        jTFVarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBVarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSaldo)
                    .addComponent(jLSaldo))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVarios)
                    .addComponent(jTFVarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jBVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Evento de pulsar el boton ingresar o retirar
     * dependiendo del diferenciador
     * @param evt 
     */
    private void jBVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVariosActionPerformed
        if (diferenciador.equals("Retirar")){
            
            //validamos si es un dato correcto
            if (validarDouble(jTFVarios.getText())){
                
                //buscamos la cuenta que esta marcada en el checkbox
                for (CuentaBancaria obj : AplicacionCuentaBancaria.cuentaBancaria.getListadoObjetos()) {
                    if (obj.getCcc().equals(cuenta)){
                        //si el saldo es mayor de lo que se quiere retirar
                        if (obj.getSaldo()>=Double.parseDouble(jTFVarios.getText())){
                            
                            //modificamos saldo
                            obj.setSaldo(obj.getSaldo()-Double.parseDouble(jTFVarios.getText()));

                            //modificamos la tabla de las cuentas
                            AplicacionCuentaBancaria.cuentaBancaria.datosTabla.setValueAt
                                (obj.getSaldo()
                                        ,AplicacionCuentaBancaria.vPrincipal.jComboBox1.getSelectedIndex(),
                                            2);

                            mostrarMensaje(this, "Se ha realizado una retirada de "+jTFVarios.getText()+"€");
                        
                        } else {
                            mostrarMensaje(this, "No se puede retirar una cantidad mayor que el saldo que tiene la cuenta");
                        }    
                    }

                }
            }
        }
        
        if (diferenciador.equals("Ingresar")){
            //validamos si es un dato correcto
            if (validarDouble(jTFVarios.getText())){
                
                //buscamos la cuenta que esta marcada en el checkbox
                for (CuentaBancaria obj : AplicacionCuentaBancaria.cuentaBancaria.getListadoObjetos()) {
                    if (obj.getCcc().equals(cuenta)){

                        //modificamos saldo
                        obj.setSaldo(obj.getSaldo()+Double.parseDouble(jTFVarios.getText()));

                        //modificamos la tabla de las cuentas
                        AplicacionCuentaBancaria.cuentaBancaria.datosTabla.setValueAt
                            (obj.getSaldo()
                                    ,AplicacionCuentaBancaria.vPrincipal.jComboBox1.getSelectedIndex(),
                                        2);

                        mostrarMensaje(this, "Se ha realizado un ingreso de "+jTFVarios.getText()+"€");
                    }

                }
            }
        }
    }//GEN-LAST:event_jBVariosActionPerformed

    /**
     * valida que sea un double y que no sea negativo
     * @param dato: el saldo que hay que retirar/ingresar 
     * @return true si es un double positivo
     */
    public boolean validarDouble(String dato){
        try{
            double aaa=Double.parseDouble(dato); 
            if (aaa<0){
                mostrarMensaje(this, "El campo no puede ser negativo");
                return false;
            } else if (aaa==0){
                mostrarMensaje(this, "No se puede ingresar o retirar 0€");
                return false;
            }
            
        } catch (Exception ex){
            mostrarMensaje(this, "El campo del ingreso no tiene un formato valido");
            return false;
        }
        return true;
    }
    
    /**
     * para mostrar mensajes de error
     * @param frame
     * @param mens 
     */
    public void mostrarMensaje(JPanel frame,String mens){
        JOptionPane.showMessageDialog(frame, mens, "Información del sistema", 
                JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVarios;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLVarios;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTextField jTFVarios;
    // End of variables declaration//GEN-END:variables
}
