
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nacho
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    VentanaDatosCuenta ventanaDatos;
    VentanaAltaCuenta ventanaAlta;
    VentanaListadoCuentas ventanaListado;
    VentanaVarios ventanaVarios;
    JButton botonprueba;
    
    //creamos las instancias de las ventanas secundarias
    public VentanaPrincipal() {
        initComponents();
        ventanaDatos = new VentanaDatosCuenta();
        ventanaAlta = new VentanaAltaCuenta();
        ventanaListado = new VentanaListadoCuentas();
        ventanaVarios = new VentanaVarios();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPBotones = new javax.swing.JPanel();
        botonConsultaSaldo = new javax.swing.JButton();
        botonDatosCuenta = new javax.swing.JButton();
        botonRetirarEfectivo = new javax.swing.JButton();
        botonAbrirNuevaCuenta = new javax.swing.JButton();
        botonListadoCuentas = new javax.swing.JButton();
        botonIngreso = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTEscritorio = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion Cuenta Bancaria");
        setResizable(false);

        jPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jPBotones.setBackground(new java.awt.Color(102, 102, 102));
        jPBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPBotones.setFocusable(false);
        jPBotones.setPreferredSize(new java.awt.Dimension(100, 300));

        botonConsultaSaldo.setText("Consulta de saldo");
        botonConsultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaSaldoActionPerformed(evt);
            }
        });

        botonDatosCuenta.setText("Datos de la cuenta");
        botonDatosCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDatosCuentaActionPerformed(evt);
            }
        });

        botonRetirarEfectivo.setText("Retirar efectivo");
        botonRetirarEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetirarEfectivoActionPerformed(evt);
            }
        });

        botonAbrirNuevaCuenta.setText("Abrir nueva cuenta");
        botonAbrirNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirNuevaCuentaActionPerformed(evt);
            }
        });

        botonListadoCuentas.setText("Listado de cuentas disponibles");
        botonListadoCuentas.setPreferredSize(new java.awt.Dimension(190, 23));
        botonListadoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoCuentasActionPerformed(evt);
            }
        });

        botonIngreso.setText("Ingreso en cuenta");
        botonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jComboBox1.setModel(AplicacionCuentaBancaria.cuentaBancaria.modeloLista);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuenta");

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(botonListadoCuentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(botonDatosCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRetirarEfectivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultaSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAbrirNuevaCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(botonAbrirNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListadoCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDatosCuenta)
                .addGap(18, 18, 18)
                .addComponent(botonIngreso)
                .addGap(18, 18, 18)
                .addComponent(botonRetirarEfectivo)
                .addGap(18, 18, 18)
                .addComponent(botonConsultaSaldo)
                .addGap(101, 101, 101)
                .addComponent(botonSalir)
                .addGap(21, 21, 21))
        );

        jTEscritorio.setBackground(new java.awt.Color(204, 204, 204));
        jTEscritorio.setRollover(true);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTEscritorio.getAccessibleContext().setAccessibleParent(jPBotones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonDatosCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosCuentaActionPerformed
        
        jTEscritorio.removeAll();
        
        jTEscritorio.add(ventanaDatos.VentanaElegirCuenta(jComboBox1.getSelectedItem().toString()));
        
        SwingUtilities.updateComponentTreeUI(this); 
        //paintAll(this.getGraphics()); 
        
    }//GEN-LAST:event_botonDatosCuentaActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonAbrirNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirNuevaCuentaActionPerformed
        jTEscritorio.removeAll();
        
        jTEscritorio.add( ventanaAlta.VentanaAltaCuenta("Abrir nueva cuenta"));
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_botonAbrirNuevaCuentaActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonListadoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoCuentasActionPerformed
        
        jTEscritorio.removeAll();
        
        jTEscritorio.add(ventanaListado.VentanaListadoCuentas("Listado de cuentas"));
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_botonListadoCuentasActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        jTEscritorio.removeAll();
        
        jTEscritorio.add(ventanaVarios.VentanaVarios("Ingresar",jComboBox1.getSelectedItem().toString()));
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_botonIngresoActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonRetirarEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetirarEfectivoActionPerformed
        jTEscritorio.removeAll();
        
        jTEscritorio.add(ventanaVarios.VentanaVarios("Retirar",jComboBox1.getSelectedItem().toString()));
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_botonRetirarEfectivoActionPerformed

    //borramos lo que haya pintado, y añadimos el panel solicitado, repintando el panel secundario de nuevo
    private void botonConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaSaldoActionPerformed
        jTEscritorio.removeAll();
        
        jTEscritorio.add(ventanaVarios.VentanaVarios("Saldo",jComboBox1.getSelectedItem().toString()));
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_botonConsultaSaldoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirNuevaCuenta;
    private javax.swing.JButton botonConsultaSaldo;
    private javax.swing.JButton botonDatosCuenta;
    private javax.swing.JButton botonIngreso;
    private javax.swing.JButton botonListadoCuentas;
    private javax.swing.JButton botonRetirarEfectivo;
    private javax.swing.JButton botonSalir;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPanel;
    private javax.swing.JToolBar jTEscritorio;
    // End of variables declaration//GEN-END:variables
}
